ROOT_DIR = '/home/neil/squeezeSeg/Camvid/CamVid/'
IMG_WIDTH = 512

NUM_CLASSES=4
ARGS_NUM_WORKERS = 10
ARGS_TRAIN_BATCH_SIZE=7
ARGS_VAL_BATCH_SIZE=1

ARGS_MODEL = 'SqueezeSeg_1/'
ARGS_SAVE_DIR = '/home/neil/squeezeSeg/Saved_model/' 
ARGS_TRAIN_DIR = '/home/neil/squeezeSeg/'
ARGS_CUDA = True

OPT_LEARNING_RATE_INIT 	= 5e-3

OPT_BETAS 		= (0.9, 0.999)
OPT_EPS_LOW 		= 1e-08
OPT_WEIGHT_DECAY 	= 1e-4

ARGS_NUM_EPOCHS = 1000
